import 'rule_document.dart';

/// Static catalog backing the Règles page. See `RuleDocument` for the
/// shape and `local_assets/rules/README.md` for the PDF-file convention.
final List<RuleDocument> kRuleDocuments = [
  RuleDocument(
    id: 'warhammer-40000-core-rules',
    title: 'Warhammer 40,000 – Édition 11',
    category: RuleCategory.mainRules,
    version: '11.0',
    releaseDate: DateTime(2025, 7, 16),
    lastUpdate: DateTime(2025, 7, 16),
    language: 'Anglais',
    isCurrent: true,
    isUpToDate: true,
    publisher: 'Games Workshop',
    downloads: 12400,
    errataCount: 0,
    localAssetId: 'warhammer-40000-core-rules',
  ),
  RuleDocument(
    id: 'missions-pack-leviathan',
    title: 'Missions Pack – Leviathan',
    category: RuleCategory.missions,
    version: '1.2',
    releaseDate: DateTime(2024, 3, 2),
    lastUpdate: DateTime(2024, 3, 2),
    language: 'Français',
    isCurrent: false,
    isUpToDate: true,
    publisher: 'Games Workshop',
    downloads: 8700,
    errataCount: 0,
  ),
  RuleDocument(
    id: 'munitorum-field-manual-2024',
    title: 'Munitorum Field Manual 2024',
    category: RuleCategory.pointsAndProfiles,
    version: '1.0',
    releaseDate: DateTime(2024, 2, 20),
    lastUpdate: DateTime(2024, 2, 20),
    language: 'Français',
    isCurrent: false,
    isUpToDate: true,
    publisher: 'Games Workshop',
    downloads: 6100,
    errataCount: 0,
  ),
  RuleDocument(
    id: 'chapter-approved-2024',
    title: 'Chapter Approved 2024',
    category: RuleCategory.errata,
    version: '1.1',
    releaseDate: DateTime(2024, 1, 10),
    lastUpdate: DateTime(2024, 1, 10),
    language: 'Français',
    isCurrent: false,
    isUpToDate: true,
    publisher: 'Games Workshop',
    downloads: 5300,
    errataCount: 0,
  ),
  RuleDocument(
    id: 'warhammer-40000-index-factions',
    title: 'Warhammer 40,000 – Index des Factions',
    category: RuleCategory.mainRules,
    version: '10.2.0',
    releaseDate: DateTime(2023, 11, 1),
    lastUpdate: DateTime(2023, 11, 1),
    language: 'Français',
    isCurrent: false,
    isUpToDate: true,
    publisher: 'Games Workshop',
    downloads: 3900,
    errataCount: 0,
  ),
  RuleDocument(
    id: 'faqs-core-rules',
    title: 'FAQs – Édition 11',
    category: RuleCategory.faqs,
    version: '1.0',
    releaseDate: DateTime(2025, 7, 16),
    lastUpdate: DateTime(2025, 7, 16),
    language: 'Anglais',
    isCurrent: false,
    isUpToDate: true,
    publisher: 'Games Workshop',
    downloads: 4200,
    errataCount: 0,
  ),
];
